{
 "title": "MySQL Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(mysql_global_status_threads_connected / mysql_global_variables_max_connections) * 100"
      }
     ]
    },
    {
     "title": "Buffer Pool Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(mysql_global_status_innodb_buffer_pool_bytes_data / mysql_global_variables_innodb_buffer_pool_size) * 100"
      }
     ]
    },
    {
     "title": "Buffer Pool Hits Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(1 - (mysql_global_status_innodb_buffer_pool_reads / mysql_global_status_innodb_buffer_pool_read_requests)) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Log",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_innodb_log_writes[1m])",
       "legendFormat": "InnoDB Log write"
      },
      {
       "expr": "irate(mysql_global_status_innodb_log_write_requests[1m])",
       "legendFormat": "InnoDB Log write requests"
      },
      {
       "expr": "irate(mysql_global_status_innodb_os_log_written[1m])",
       "legendFormat": "InnoDB Log written bytes"
      },
      {
       "expr": "irate(mysql_global_status_innodb_log_waits[1m])",
       "legendFormat": "InnoDB Log waited write"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"select\"}[1m])",
       "legendFormat": "Select"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"insert\"}[1m])",
       "legendFormat": "Insert"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"update\"}[1m])",
       "legendFormat": "Update"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"delete\"}[1m])",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"begin\"}[1m])",
       "legendFormat": "Begin"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"commit\"}[1m])",
       "legendFormat": "Commit"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"rollback\"}[1m])",
       "legendFormat": "Rollback"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"savepoint\"}[1m])",
       "legendFormat": "Savepoint"
      },
      {
       "expr": "irate(mysql_global_status_commands_total{command=\"rollback_to_savepoint\"}[1m])",
       "legendFormat": "Rollback savepoint"
      }
     ]
    },
    {
     "title": "Slow Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_slow_queries[1m])",
       "legendFormat": "Slow Queries"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_threads_connected",
       "legendFormat": "current connection"
      },
      {
       "expr": "mysql_global_status_threads_running",
       "legendFormat": "thread running"
      },
      {
       "expr": "mysql_global_variables_max_connections",
       "legendFormat": "max connection"
      }
     ]
    },
    {
     "title": "Thread Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_threads_cached",
       "legendFormat": "current thread cache size"
      },
      {
       "expr": "mysql_global_variables_thread_cache_size",
       "legendFormat": "max thread cache size"
      }
     ]
    }
   ]
  },
  {
   "title": "InnoDB Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Buffer Pool Status",
     "type": "graph",
     "description": "InnoDB Buffer Pool Status provides ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_buffer_pool_size",
       "legendFormat": "Total buffer pool size"
      },
      {
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_data",
       "legendFormat": "Buffer pool used"
      },
      {
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty",
       "legendFormat": "Buffer pool dirty"
      }
     ]
    },
    {
     "title": "InnoDB Flusing",
     "type": "graph",
     "description": "On InnoDB, page cleaner threads start pre-flushing dirty page when dirty page rate reaches innodb_max_dirty_pages_pct_lwm.\n\nMoreover, they force dirty page flushed when dirty page rate reaches innodb_max_dirty_pages_pct, which operation cost is very high.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_variables_innodb_max_dirty_pages_pct",
       "legendFormat": "flush threshold"
      },
      {
       "expr": "mysql_global_variables_innodb_max_dirty_pages_pct_lwm",
       "legendFormat": "preflush threshold"
      },
      {
       "expr": "(mysql_global_status_innodb_buffer_pool_bytes_dirty / mysql_global_variables_innodb_buffer_pool_size) * 100",
       "legendFormat": "dirty page rate"
      }
     ]
    },
    {
     "title": "InnoDB Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_innodb_buffer_pool_read_requests[1m])",
       "legendFormat": "read request"
      },
      {
       "expr": "irate(mysql_global_status_innodb_buffer_pool_reads[1m])",
       "legendFormat": "read from disk"
      },
      {
       "expr": "irate(mysql_global_status_innodb_buffer_pool_write_requests[1m])",
       "legendFormat": "write request"
      },
      {
       "expr": "irate(mysql_global_status_innodb_pages_written[1m])",
       "legendFormat": "flushed page"
      }
     ]
    },
    {
     "title": "InnoDB Row Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(mysql_global_status_innodb_row_ops_total{operation=\"read\"}[1m])",
       "legendFormat": "read rows"
      },
      {
       "expr": "irate(mysql_global_status_innodb_row_ops_total{operation=\"inserted\"}[1m])",
       "legendFormat": "insert tows"
      },
      {
       "expr": "irate(mysql_global_status_innodb_row_ops_total{operation=\"updated\"}[1m])",
       "legendFormat": "update rows"
      },
      {
       "expr": "irate(mysql_global_status_innodb_row_ops_total{operation=\"deleted\"}[1m])",
       "legendFormat": "delete rows"
      }
     ]
    }
   ]
  }
 ]
}